import io
import zlib
from datetime import datetime

class PurePDFBuilder:
    """
    Pure Python vector PDF (v1.4) document builder.
    Requires ZERO external C-extensions, fully standard compliant, and renders
    crisp multi-page documents with headers, tables, colored callouts, and footers.
    """
    def __init__(self, page_width=595.28, page_height=841.89): # A4
        self.width = page_width
        self.height = page_height
        self.margin_left = 42.0
        self.margin_right = 42.0
        self.margin_top = 45.0
        self.margin_bottom = 45.0
        self.content_width = self.width - self.margin_left - self.margin_right
        
        self.pages = []
        self.current_stream = []
        self.cursor_y = self.height - self.margin_top
        self.page_number = 0
        self.start_new_page()

    def start_new_page(self):
        if self.current_stream:
            self.pages.append("".join(self.current_stream))
            self.current_stream = []
        
        self.page_number += 1
        self.cursor_y = self.height - self.margin_top
        
        # Draw Top Accent Header Line
        self.set_fill_color(0.145, 0.388, 0.922) # #2563EB
        self.draw_rect(self.margin_left, self.height - 24, self.content_width, 3, fill=True, stroke=False)
        
        # Running Header
        self.draw_text("DFD ARCHITECT — SYSTEM SPECIFICATION", self.margin_left, self.height - 20, font="F2", size=7, color=(0.4, 0.45, 0.55))
        
        # Running Footer
        self.draw_text(f"Page {self.page_number}", self.width - self.margin_right - 40, 22, font="F1", size=8, color=(0.5, 0.5, 0.5))
        self.draw_text("Generated by DFD Architect • Design. Document. Validate. Visualize.", self.margin_left, 22, font="F1", size=7.5, color=(0.5, 0.5, 0.5))
        self.draw_line(self.margin_left, 32, self.width - self.margin_right, 32, color=(0.85, 0.88, 0.92), width=0.5)

    def check_page_break(self, needed_height):
        if (self.cursor_y - needed_height) < self.margin_bottom:
            self.start_new_page()

    # --- Drawing Primitives ---
    def set_fill_color(self, r, g, b):
        self.current_stream.append(f"{r:.3f} {g:.3f} {b:.3f} rg\n")

    def set_stroke_color(self, r, g, b):
        self.current_stream.append(f"{r:.3f} {g:.3f} {b:.3f} RG\n")

    def draw_rect(self, x, y, w, h, fill=True, stroke=False, color=(0.9, 0.9, 0.9), stroke_color=(0.7, 0.7, 0.7), line_width=1.0):
        if fill:
            self.set_fill_color(*color)
        if stroke:
            self.set_stroke_color(*stroke_color)
            self.current_stream.append(f"{line_width:.2f} w\n")
        
        op = "b\n" if (fill and stroke) else ("f\n" if fill else "s\n")
        self.current_stream.append(f"{x:.2f} {y:.2f} {w:.2f} {h:.2f} re\n{op}")

    def draw_line(self, x1, y1, x2, y2, color=(0.8, 0.8, 0.8), width=1.0):
        self.set_stroke_color(*color)
        self.current_stream.append(f"{width:.2f} w\n{x1:.2f} {y1:.2f} m {x2:.2f} {y2:.2f} l S\n")

    def escape_pdf_text(self, text):
        if not text:
            return ""
        # Clean non-ascii to ascii or safe string
        clean = ""
        for char in str(text):
            if char in "()\\":
                clean += "\\" + char
            elif 32 <= ord(char) <= 126:
                clean += char
            elif char == '\n':
                clean += ' '
            elif ord(char) == 8220 or ord(char) == 8221:
                clean += '"'
            elif ord(char) == 8216 or ord(char) == 8217:
                clean += "'"
            elif ord(char) == 8211 or ord(char) == 8212:
                clean += "-"
            elif ord(char) == 8226:
                clean += "*"
            else:
                clean += " "
        return clean

    def draw_text(self, text, x, y, font="F1", size=10, color=(0.12, 0.16, 0.23)):
        escaped = self.escape_pdf_text(text)
        self.set_fill_color(*color)
        self.current_stream.append(f"BT /{font} {size:.1f} Tf {x:.2f} {y:.2f} Td ({escaped}) Tj ET\n")

    # --- High Level Document Blocks ---
    def add_title(self, title, subtitle=None):
        self.check_page_break(60)
        # Background Accent Box
        self.draw_rect(self.margin_left, self.cursor_y - 48, self.content_width, 54, fill=True, stroke=True, color=(0.95, 0.97, 1.0), stroke_color=(0.8, 0.88, 0.98))
        self.draw_rect(self.margin_left, self.cursor_y - 48, 4, 54, fill=True, stroke=False, color=(0.145, 0.388, 0.922))
        
        self.draw_text(title, self.margin_left + 14, self.cursor_y - 20, font="F2", size=18, color=(0.118, 0.227, 0.541))
        if subtitle:
            self.draw_text(subtitle, self.margin_left + 14, self.cursor_y - 38, font="F3", size=10.5, color=(0.3, 0.38, 0.48))
        
        self.cursor_y -= 64

    def add_heading_1(self, text):
        self.check_page_break(36)
        self.cursor_y -= 10
        self.draw_text(text, self.margin_left, self.cursor_y, font="F2", size=13, color=(0.145, 0.388, 0.922))
        self.draw_line(self.margin_left, self.cursor_y - 4, self.width - self.margin_right, self.cursor_y - 4, color=(0.85, 0.9, 0.96), width=1.0)
        self.cursor_y -= 18

    def add_heading_2(self, text):
        self.check_page_break(28)
        self.cursor_y -= 6
        self.draw_text(text, self.margin_left, self.cursor_y, font="F2", size=10.5, color=(0.15, 0.2, 0.3))
        self.cursor_y -= 14

    def add_paragraph(self, text, size=9, color=(0.2, 0.25, 0.32)):
        # Basic word wrap
        words = str(text).split()
        max_chars_per_line = int(self.content_width / (size * 0.48))
        
        lines = []
        cur_line = []
        cur_len = 0
        for w in words:
            if cur_len + len(w) + 1 > max_chars_per_line:
                lines.append(" ".join(cur_line))
                cur_line = [w]
                cur_len = len(w)
            else:
                cur_line.append(w)
                cur_len += len(w) + 1
        if cur_line:
            lines.append(" ".join(cur_line))

        for line in lines:
            self.check_page_break(size + 4)
            self.draw_text(line, self.margin_left, self.cursor_y, font="F1", size=size, color=color)
            self.cursor_y -= (size + 4)
        self.cursor_y -= 4

    def add_callout(self, title, body_lines, is_error=False):
        box_h = 24 + len(body_lines) * 13
        self.check_page_break(box_h + 10)
        
        bg = (0.99, 0.95, 0.95) if is_error else (0.94, 0.99, 0.95)
        border = (0.86, 0.15, 0.15) if is_error else (0.02, 0.59, 0.41)
        
        self.draw_rect(self.margin_left, self.cursor_y - box_h, self.content_width, box_h, fill=True, stroke=True, color=bg, stroke_color=(0.85, 0.9, 0.88))
        self.draw_rect(self.margin_left, self.cursor_y - box_h, 4, box_h, fill=True, stroke=False, color=border)
        
        self.draw_text(title, self.margin_left + 12, self.cursor_y - 14, font="F2", size=9.5, color=border)
        cy = self.cursor_y - 28
        for bl in body_lines:
            self.draw_text(bl, self.margin_left + 12, cy, font="F1", size=8.5, color=(0.15, 0.2, 0.25))
            cy -= 13
        
        self.cursor_y -= (box_h + 10)

    def add_table(self, headers, rows, col_pcts=None):
        if not col_pcts:
            col_pcts = [1.0 / len(headers)] * len(headers)
        
        col_widths = [p * self.content_width for p in col_pcts]
        row_height = 18.0
        
        # Check space for at least header + 1 row
        self.check_page_break(row_height * 2.5)

        # Header
        self.draw_rect(self.margin_left, self.cursor_y - row_height, self.content_width, row_height, fill=True, stroke=False, color=(0.145, 0.388, 0.922))
        
        curr_x = self.margin_left
        for idx, h in enumerate(headers):
            w = col_widths[idx]
            self.draw_text(h, curr_x + 5, self.cursor_y - 12, font="F2", size=8.5, color=(1.0, 1.0, 1.0))
            curr_x += w
        
        self.cursor_y -= row_height

        # Rows
        for r_idx, row in enumerate(rows):
            self.check_page_break(row_height)
            
            fill_col = (0.97, 0.98, 0.99) if (r_idx % 2 == 1) else (1.0, 1.0, 1.0)
            self.draw_rect(self.margin_left, self.cursor_y - row_height, self.content_width, row_height, fill=True, stroke=False, color=fill_col)
            self.draw_line(self.margin_left, self.cursor_y - row_height, self.width - self.margin_right, self.cursor_y - row_height, color=(0.88, 0.9, 0.93), width=0.5)

            curr_x = self.margin_left
            for idx, cell in enumerate(row):
                w = col_widths[idx]
                val_str = str(cell) if cell is not None else ""
                # truncate if too long
                max_chars = int(w / 5.2)
                if len(val_str) > max_chars:
                    val_str = val_str[:max_chars - 2] + ".."
                
                self.draw_text(val_str, curr_x + 5, self.cursor_y - 12, font="F1", size=8, color=(0.15, 0.2, 0.25))
                curr_x += w
            
            self.cursor_y -= row_height

        self.cursor_y -= 8

    def build_pdf_stream(self):
        """Assembles and cross-references pure PDF byte stream."""
        if self.current_stream:
            self.pages.append("".join(self.current_stream))
            self.current_stream = []

        total_pages = len(self.pages)
        objects = []

        # Object 1: Catalog
        objects.append("<< /Type /Catalog /Pages 2 0 R >>")
        
        # Object 2: Pages
        kids_refs = " ".join([f"{3 + i * 2} 0 R" for i in range(total_pages)])
        objects.append(f"<< /Type /Pages /Kids [{kids_refs}] /Count {total_pages} >>")

        # Fonts definition (Obj 3 + total_pages * 2 onwards)
        font_base_idx = 3 + total_pages * 2

        # Pages & Content Streams
        for i in range(total_pages):
            page_obj_idx = 3 + i * 2
            content_obj_idx = 4 + i * 2
            
            # Page Object
            objects.append(f"""<< /Type /Page
/Parent 2 0 R
/MediaBox [0 0 {self.width:.2f} {self.height:.2f}]
/Contents {content_obj_idx} 0 R
/Resources <<
  /Font <<
    /F1 {font_base_idx} 0 R
    /F2 {font_base_idx + 1} 0 R
    /F3 {font_base_idx + 2} 0 R
  >>
>>
>>""")
            # Content Stream Object
            raw_content = self.pages[i].encode('latin-1', 'replace')
            compressed = zlib.compress(raw_content)
            objects.append(f"<< /Length {len(compressed)} /Filter /FlateDecode >>\nstream\n" + compressed.decode('latin-1') + "\nendstream")

        # Fonts (Helvetica, Helvetica-Bold, Helvetica-Oblique)
        objects.append("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")
        objects.append("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>")
        objects.append("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique /Encoding /WinAnsiEncoding >>")

        # Assemble PDF file with correct byte offsets in xref table
        out = io.BytesIO()
        out.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
        
        offsets = []
        for idx, obj in enumerate(objects):
            offsets.append(out.tell())
            obj_num = idx + 1
            if isinstance(obj, str):
                obj_bytes = f"{obj_num} 0 obj\n{obj}\nendobj\n".encode('latin-1', 'replace')
            else:
                obj_bytes = obj
            out.write(obj_bytes)

        xref_offset = out.tell()
        out.write(f"xref\n0 {len(objects) + 1}\n".encode('latin-1'))
        out.write(b"0000000000 65535 f \n")
        for off in offsets:
            out.write(f"{off:010d} 00000 n \n".encode('latin-1'))

        trailer = f"""trailer
<<
  /Size {len(objects) + 1}
  /Root 1 0 R
>>
startxref
{xref_offset}
%%EOF
"""
        out.write(trailer.encode('latin-1'))
        out.seek(0)
        return out


def generate_pdf_stream(doc_data):
    """
    Generates a high-quality, professional PDF document from project documentation.
    """
    pdf = PurePDFBuilder()
    
    meta = doc_data.get('project_meta', {})
    metrics = doc_data.get('summary_metrics', {})
    entities = doc_data.get('entities', [])
    processes = doc_data.get('processes', [])
    datastores = doc_data.get('datastores', [])
    flows = doc_data.get('data_flows', [])
    validation = doc_data.get('validation', {})
    narrative_specs = doc_data.get('narrative_specs', [])

    # Header Card
    pdf.add_title(
        meta.get('name', 'System Data Flow Diagram'),
        f"Data Flow Diagram Specification Document — {meta.get('dfd_level', 'Level 1')}"
    )

    # Metadata Grid
    pdf.add_table(
        ["Specification Attribute", "System Value"],
        [
            ["System Name", meta.get('system_name', 'N/A')],
            ["Author / Architect", meta.get('author', 'Software Architect')],
            ["Version / Release", meta.get('version', '1.0.0')],
            ["DFD Level", meta.get('dfd_level', 'Level 1')],
            ["Tags / Modules", meta.get('tags', 'General')],
            ["Generated Date", meta.get('updated_at', datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'))]
        ],
        col_pcts=[0.35, 0.65]
    )

    # 1. System Overview & Scope
    pdf.add_heading_1("1. System Overview & Scope")
    pdf.add_paragraph(meta.get('description', 'This document specifies the system data flows, processes, data stores, and entities.'))

    # 2. Summary Metrics
    pdf.add_heading_1("2. Executive Summary Metrics")
    pdf.add_table(
        ["Component Type", "Count", "Description"],
        [
            ["External Entities", str(metrics.get('total_entities', 0)), "External systems, users, and boundaries"],
            ["Processes", str(metrics.get('total_processes', 0)), "Business logic transformations & computational tasks"],
            ["Data Stores", str(metrics.get('total_datastores', 0)), "Persistent repositories, databases, and caches"],
            ["Data Flows", str(metrics.get('total_flows', 0)), "Directed information transfer pathways"],
            ["Decomposition Levels", str(metrics.get('total_levels', 1)), "Hierarchy depth (Context Level 0 to Level 2)"],
            ["Compliance Score", f"{validation.get('summary', {}).get('compliance_score', 100)}%", "Standard DFD syntactic & semantic adherence"]
        ],
        col_pcts=[0.30, 0.15, 0.55]
    )

    # 3. External Entities
    pdf.add_heading_1("3. External Entities & Data Sources")
    if entities:
        rows = [[e.get('identifier', '-'), e.get('name', '-'), e.get('entity_type', 'Actor'), e.get('description', '-')] for e in entities]
        pdf.add_table(["ID", "Entity Name", "Category", "System Role"], rows, col_pcts=[0.12, 0.28, 0.25, 0.35])
    else:
        pdf.add_paragraph("No external entities defined.")

    # 4. Processes
    pdf.add_heading_1("4. Processes & Functional Decomposition")
    if processes:
        rows = [[p.get('identifier', '-'), p.get('name', '-'), p.get('level_name', 'Level 1'), p.get('description', '-')] for p in processes]
        pdf.add_table(["#", "Process Label", "Level", "Description"], rows, col_pcts=[0.12, 0.30, 0.20, 0.38])
    else:
        pdf.add_paragraph("No processes defined.")

    # 5. Data Stores
    pdf.add_heading_1("5. Data Stores & Schema")
    if datastores:
        rows = [[d.get('identifier', '-'), d.get('name', '-'), d.get('storage_type', 'DB'), d.get('description', '-')] for d in datastores]
        pdf.add_table(["ID", "Data Store Label", "Engine", "Description & Contents"], rows, col_pcts=[0.12, 0.28, 0.22, 0.38])
    else:
        pdf.add_paragraph("No data stores defined.")

    # 6. Data Flows & Data Dictionary
    pdf.add_heading_1("6. Data Flows & Data Dictionary")
    if flows:
        rows = [[f.get('identifier', '-'), f.get('name', '-'), f.get('source_name', '-'), f.get('destination_name', '-'), f.get('data_type', 'Data'), f.get('description', '-')] for f in flows]
        pdf.add_table(["ID", "Flow Name", "Source", "Destination", "Type", "Payload Description"], rows, col_pcts=[0.10, 0.22, 0.17, 0.17, 0.14, 0.20])
    else:
        pdf.add_paragraph("No data flows mapped.")

    # 7. Narrative Specs
    if narrative_specs:
        pdf.add_heading_1("7. Detailed Process Specifications")
        for spec in narrative_specs:
            pdf.add_heading_2(f"Process {spec.get('identifier', '')}: {spec.get('name', '')}")
            inputs = ", ".join(spec.get('incoming_flows', [])) or "None"
            outputs = ", ".join(spec.get('outgoing_flows', [])) or "None"
            pdf.add_callout(
                f"Specification: {spec.get('name', '')}",
                [
                    f"Description: {spec.get('description', 'N/A')}",
                    f"Incoming Data Flows: {inputs}",
                    f"Outgoing Data Flows: {outputs}"
                ]
            )

    # 8. Validation Audit
    pdf.add_heading_1("8. DFD Syntax & Rule Compliance Audit")
    summary = validation.get('summary', {})
    score = summary.get('compliance_score', 100)
    errors = summary.get('errors_count', 0)
    warnings = summary.get('warnings_count', 0)
    passed = summary.get('passed_count', 0)

    pdf.add_callout(
        f"Validation Audit Result: {score}% Compliant",
        [
            f"Rules Passed: {passed} checks verified",
            f"Warnings: {warnings} semantic recommendations",
            f"Critical Errors: {errors} blocking rule violations"
        ],
        is_error=(errors > 0)
    )

    issues = validation.get('issues', [])
    if issues:
        pdf.add_heading_2("Identified Compliance Issues & Recommendations")
        issue_rows = [[iss.get('type', 'Warning').upper(), iss.get('title', '-'), iss.get('message', '-'), iss.get('suggestion', '-')] for iss in issues]
        pdf.add_table(["Severity", "Violation", "Message", "Fix Recommendation"], issue_rows, col_pcts=[0.14, 0.26, 0.32, 0.28])

    return pdf.build_pdf_stream()
